### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-bootcamp#1]
@Valentin-Miroshnichenko I just have to say this is completely amazing work from you!
This is mind blowing detailed work <3

**Comment by rogeralsing** [comment]
For legal reasons and licenses, are there any parts of this based of the Akka.NET Bootcamp? if so, this should be explicitly mentioned in a proper License file.

**Comment by Valentin-Miroshnichenko** [comment]
No, just the first page. A little bit like to Akka =) https://github.com/AsynkronIT/protoactor-bootcamp/tree/master/C%23/ENG

**Comment by rogeralsing** [comment]
I'm currently reworking all documentation here: https://asynkron.se/docs/proto.actor/

Do you think it would make sense to copy some of the bootcamp content into the core documentation?
