### ISSUE TITLE
"Link error"  in Module 8 

### ISSUE THREAD

**Issue by Shawn-Fan** [AsynkronIT/protoactor-bootcamp#2]
Thanks for the great materials, but parts of link in Module 8 (lesson 4, 5, 6, 7, 8) do not work.

**Comment by Valentin-Miroshnichenko** [comment]
I know. Currently, I work on refresh and added functionality to the python version of Proto.Actor. And when I'm done with it. I'll add a bootcamp version for python and I fixed this issue for the C# version.

**Comment by Shawn-Fan** [comment]
Looking forward to seeing your update in the future.

**Comment by cupen** [comment]
@Valentin-Miroshnichenko  Hello :smiley:  .
Thank you for your nice work.
How is your `bootcamp version for python` would be?  Is it consists by the words of C# version and python code?

**Comment by Valentin-Miroshnichenko** [comment]
**How is your bootcamp version for python would be?**
I am waiting for the guys to finish the C# version of Cluster to port it to Python and write the documentation.
**Is it consists by the words of C# version and python code?**
Yes

**Comment by cupen** [comment]
@Valentin-Miroshnichenko  Thx,  I get it.
