### ISSUE TITLE
Bootcamp Not Accessible

### ISSUE THREAD

**Issue by kkadir** [AsynkronIT/protoactor-bootcamp#9]
The Bootcamp URL (https://proto.actor/docs/bootcamp/) redirects to a Page Not Found error page:
![image](https://user-images.githubusercontent.com/8139167/157041715-d945033d-4ea9-4265-954e-9c1550cd4282.png)

**Comment by rogeralsing** [comment]
It is back online. we are doing some restructuring on the website.
Sorry for the inconvenience.

**Comment by kkadir** [comment]
Thanks for the update.
